config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'myclasses#index'
  resources :myclasses, only: [:index]
  get "/myclasses/:id/signup", to: 'myclasses#signup', as: 'signup_myclass'
  get '/myclasses/multi_signup', to: 'myclasses#multi_signup', as: 'multi_signup_myclass'
  get '/myclasses/show/:id', to: 'myclasses#show', as: 'myclass'
  get '/myclasses/showbetween', to: 'myclasses#showbetween', as: 'showbetween_myclass'

  get '/myclasses/:id/score', to: 'myclasses#score', as: 'score_myclass'

  resources :attendances, only: [:create, :show]
  delete "/attendances", to: 'attendances#destroy', as: 'delete_attendance'
  post "/attendances/multi_signup", to: 'attendances#multi_signup', as: 'multi_signup_attendances'
  post '/attendances/score', to: 'attendances#score', as: 'score_attendance'

end

app/models/student.rb
class Student < ActiveRecord::Base
	has_many :attendances, dependent: :destroy
	has_many :myclasses, through: :attendances

	validates_uniqueness_of :name
	validates_presence_of :name, allow_blank: false, message: '名字不能是空白!'
end

app/controllers/myclasses_controller.rb
class MyclassesController < ApplicationController
  before_action :set_myclass, only: [:show, :edit, :update, :destroy, :signup, :score]
  before_action :set_date_time, only: [:signup]

  # GET /myclasses
  # GET /myclasses.json
  def index
    beginning_of_month = Time.zone.now.beginning_of_month
    @this_month = beginning_of_month.strftime("%B")
    @next_month = (beginning_of_month + 1.month).strftime("%B")
    @nnext_month = (beginning_of_month + 2.month).strftime("%B")

    @this_month_classes = Myclass.between(beginning_of_month, beginning_of_month + 1.month)
    @next_month_classes = Myclass.between(beginning_of_month + 1.month, beginning_of_month + 2.month)
    @nnext_month_classes = Myclass.between(beginning_of_month + 2.month, beginning_of_month + 3.month)
  end

  # GET /myclasses/1
  # GET /myclasses/1.json
  def show
  end

  # GET /myclasses/new
  def new
    @myclass = Myclass.new
  end

  # GET /myclasses/1/edit
  def edit
  end

  # POST /myclasses
  # POST /myclasses.json
  def create
    @myclass = Myclass.new(myclass_params)

    respond_to do |format|
      if @myclass.save
        format.html { redirect_to @myclass, notice: 'Myclass was successfully created.' }
        format.json { render :show, status: :created, location: @myclass }
      else
        format.html { render :new }
        format.json { render json: @myclass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /myclasses/1
  # PATCH/PUT /myclasses/1.json
  def update
    respond_to do |format|
      if @myclass.update(myclass_params)
        format.html { redirect_to @myclass, notice: 'Myclass was successfully updated.' }
        format.json { render :show, status: :ok, location: @myclass }
      else
        format.html { render :edit }
        format.json { render json: @myclass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /myclasses/1
  # DELETE /myclasses/1.json
  def destroy
    @myclass.destroy
    respond_to do |format|
      format.html { redirect_to myclasses_url, notice: 'Myclass was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /myclasses/1/signup
  def signup
    students = @myclass.students
    @safe = students[0..@myclass.limit-1]
    @back = students[@myclass.limit..-1] ? students[@myclass.limit..-1] : []

    @attend = Attendance.new

    render :signup, status: :success
  end

  # GET /myclasses/multi_signup
  def multi_signup
    @selected_classes = Myclass.find(params[:class_ids])
    @ids = params[:class_ids].join(",")
    render :multi_signup
  end

  def showbetween
    now = Time.zone.now
    @start_date = params[:start_date] ? Time.parse(params[:start_date]) : now - 1.month
    @end_date = params[:end_date] ? Time.parse(params[:end_date]) : now

    @myclasses = Myclass.between(@start_date, @end_date)
    respond_to do |format|
      format.html { render :showbetween }
      format.js
    end
  end

  def score
    # render :score
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_myclass
      @myclass = Myclass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def myclass_params
      params.require(:myclass).permit(:title, :s_time, :e_time, :limit, :classroom_id, :class_ids)
    end

    def set_date_time
      @date = @myclass.s_time.strftime("%Y/%m/%d")
      @start = @myclass.s_time.strftime("%H:%M")
      @end = @myclass.e_time.strftime("%H:%M")
    end
end

app/helpers/myclasses_helper.rb
module MyclassesHelper
end

app/views/myclasses/_class_table.html.erb
<% if classes.count > 0 %>
  <h2><%= month %></h2>
  <table class="table">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>日期</th>
        <th>上課時間</th>
        <th>已報名</th>
        <th>名額</th>
        <th>教室</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% classes.each do |myclass| %>
        <tr>
          <% if !myclass.is_expired && myclass.is_opened_for_signup %>
            <td><%= check_box_tag("class_ids[]", myclass.id)%></td>
          <% else %>
            <td></td>
          <% end %>
          <td><%= myclass.title %></td>
          <td><%= myclass.date_string %></td>
          <td><%= myclass.time_string %></td>
          <td><%= myclass.attendances.count %></td>
          <td><%= myclass.limit %></td>
          <td><%= myclass.classroom.title %></td>
          <% if myclass.is_expired %>
            <td><%= link_to "看上課內容", myclass_path(myclass) %></td>
            <td><%= link_to "跟喬巴說你多累", score_myclass_path(myclass) %></td>
          <% elsif !myclass.is_opened_for_signup %>
            <td colspan="2"><%= "%{s} 之後開放報名" % { s: myclass.signup_date_string }%></td>
          <% else %>
            <td><%= link_to '報名/取消', signup_myclass_path(myclass) %></td>
            <td><a href="#" data-toggle="tooltip" data-html="true" title="<%= render 'students', :myclass => myclass %>">看有誰上課</a></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/myclasses/_form.html.erb
<%= form_for(@myclass) do |f| %>
  <% if @myclass.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@myclass.errors.count, "error") %> prohibited this myclass from being saved:</h2>

      <ul>
      <% @myclass.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :s_time %><br>
    <%= f.time_select :s_time %>
  </div>
  <div class="field">
    <%= f.label :e_time %><br>
    <%= f.time_select :e_time %>
  </div>
  <div class="field">
    <%= f.label :limit %><br>
    <%= f.text_field :limit %>
  </div>
  <div class="field">
    <%= f.label :classroom_id %><br>
    <%= f.text_field :classroom_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/myclasses/_list_classes.html.erb
<h2><%= @start_date.strftime('%m/%d') + " ~ " + @end_date.strftime('%m/%d') + "的課程" %></h2>
<table class='table'>
	<thead>
		<tr>
			<th>Title</th>
			<th>日期</th>
			<th>時間</th>
			<th colspan="3"></th>
		</tr>
	<thead>
	<tbody>
		<% @myclasses.each do |myclass| %>
			<tr>
				<td><%= myclass.title %></td>
				<td><%= myclass.date_string %></td>
				<td><%= myclass.time_string %></td>
				<td><%= link_to "看內容", myclass_path(myclass) %></td>
				<td><%= link_to "跟喬巴說你多累", score_myclass_path(myclass) %></td>
				<td><a href="#" data-toggle="tooltip" data-html="true" title="<%= render 'students', :myclass => myclass %>">看有誰上課</a></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/myclasses/_score_form.html.erb
<%= form_tag ({controller: "attendances", action: "score"}) do %>
    <div class="form-group">
      <%= label_tag "名字" %>
      <%= select_tag :student_id, options_from_collection_for_select(@myclass.students, "id", "name"), class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= label_tag "疲勞程度(1~10)" %>
      <%= text_field_tag :score, "", :class => 'form-control' %>
    </div>
    <%= hidden_field_tag :myclass_id, @myclass.id %>
    <%= submit_tag "送出", :class => 'btn btn-default' %>
<% end %>

app/views/myclasses/_students.html.erb
<div class='my-tooltip'>
	<% count = 1 %>
	<% myclass.attendances.order("created_at asc").each do |attendance| %>
		<%= "%{i}. %{n}" % {i: count, n: attendance.student.name} %><br>
		<% count = count + 1 %>
	<% end %>
</div>

app/views/myclasses/_time_filter.html.erb
<div class="row">
	<div class="col-md-12">
	<h1>以前的課程</h1>
		<%= form_tag({controller: "myclasses", action: "showbetween"}, method: "get", class: 'form-inline', remote: true) do %>
			<% now = Time.zone.now %>
			<div class="form-group">
		        <%= label_tag "開始日期" %>
		        <%= date_field_tag :start_date,  @start_date.strftime('%Y-%m-%d'), class: 'form-control' %>
		    </div>
		    <div class="form-group">
		        <%= label_tag "結束日期" %>
		        <%= date_field_tag :end_date, @end_date.strftime('%Y-%m-%d'), class: 'form-control' %>
		    </div>
		    <div class="form-group">
		    	<%= submit_tag "查詢", class: 'btn btn-default' %>
		    </div>
		<% end %>
	</div>
</div>

app/views/myclasses/edit.html.erb
<h1>Editing myclass</h1>

<%= render 'form' %>

<%= link_to 'Show', @myclass %> |
<%= link_to 'Back', myclasses_path %>

app/views/myclasses/index.html.erb
<h1>請選擇你想登記的課程</h1>

<%= form_tag({controller: "myclasses", action: "multi_signup"}, method: "get") do %>
  <!-- <input type="submit" value="登記選取的課程" class="btn btn-default"/> -->
  <%= render "class_table", :classes => @this_month_classes, :month => @this_month %>
  <%= render "class_table", :classes => @next_month_classes, :month => @next_month %>
  <%= render "class_table", :classes => @nnext_month_classes, :month => @nnext_month %>
  <%= submit_tag "登記選取的課程", class: "btn btn-default" %>
<% end %>
<br>

app/views/myclasses/multi_signup.html.erb
<h2>您選取的課程</h2>
<div class="row">
  <div class="col-md-6">
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>日期</th>
        <th>上課時間</th>
        <th>已報名</th>
        <th>名額</th>
        <th>教室</th>
      </tr>
    </thead>

    <tbody>
      <% @selected_classes.each do |myclass| %>
        <tr>
          <td><%= myclass.title %></td>
          <td><%= myclass.s_time.strftime("%Y/%m/%d   %a.") %></td>
          <td><%= myclass.s_time.strftime("%H:%M") + " ~ " + myclass.e_time.strftime("%H:%M") %></td>
          <td><%= myclass.attendances.count %></td>
          <td><%= myclass.limit %></td>
          <td><%= myclass.classroom.title %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>

  <div class="col-md-6">
    <%= form_tag({controller: 'attendances', action: 'multi_signup'}) do %>
      <div class="form-group">
        <%= label_tag "名字" %>
        <%= text_field_tag 'attendance[student]', '', class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= label_tag "刪除密碼" %>
        <%= password_field_tag 'attendance[password]', '', class: 'form-control' %>
      </div>

      <div class="well well-sm">
        刪除密碼的用途是，如果你後來無法來上這一堂課，要取消的時候，需要這個密碼才能把你從課程裡刪除。
        主要是避免別人不小心把你刪掉
      </div>
      <%= hidden_field_tag 'attendance[myclass_ids]', @ids %>
      <%= submit_tag "確認", class: 'btn btn-default' %>
    </div>

  <% end %>
</div>

app/views/myclasses/new.html.erb
<h1>New myclass</h1>

<%= render 'form' %>

<%= link_to 'Back', myclasses_path %>

app/views/myclasses/score.html.erb
<div class="page-header">
  <h1><%= @myclass.title %></h1>
  <p>
    <strong>時間:</strong>
    <%= @myclass.date_string + " " + @myclass.time_string %>
  </p>
  <p>
    <strong>地點:</strong>
    <%= @myclass.classroom.title %>
  </p>

</div>
<div class="row">
  <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">課程內容</h3>
        </div>
        <div class="panel-body">
          <%= @myclass.content.html_safe %>
        </div>
      </div>
  </div>
  <div class="col-md-6">
    <div class="panel panel-default">
        <div class="panel-body">
          <%= render "score_form" %>
        </div>
      </div>
  </div>
</div>

app/views/myclasses/show.html.erb
<div class="page-header">
  <h1><%= @myclass.title %></h1>

  <p>
    <strong>時間:</strong>
    <%= @myclass.date_string + " " + @myclass.time_string %>
  </p>

  <p>
    <strong>名額:</strong>
    <%= @myclass.limit %>
  </p>

  <p>
    <strong>地點:</strong>
    <%= @myclass.classroom.title %>
  </p>

  <p>
    <strong>地址:</strong>
    <%= @myclass.classroom.address %>
  </p>

</div>
<div class="row">
  <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">課程內容</h3>
        </div>
        <div class="panel-body">
          <%= @myclass.content.html_safe %>
        </div>
      </div>
  </div>
  <div class="col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">學生</h3>
        </div>
        <div class="panel-body">
          <table class='table'>
            <thead>
              <tr>
                <th>#</th>
                <th>姓名</th>
                <th>疲勞程度</th>
              </tr>
            </thead>
            <tbody>
              <% count = 0 %>
              <% @myclass.attendances.order('created_at asc').each do |attendances| %>
                <% count = count + 1 %>
                <tr>
                  <td><%= count %></td>
                  <td><%= attendances.student.name %></td>
                  <td><%= attendances.score %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
  </div>
</div>

app/views/myclasses/showbetween.html.erb
<%= render "time_filter" %>
<div class="row">
	<div class="col-md-12" id="classes">
		<%= render "list_classes" %>
	</div>
</div>

app/views/myclasses/signup.html.erb
<% if notice %>
  <p id="notice" class="alert alert-success"><%= notice %></p>
<% end %>

<div class="page-header">
  <h1><%= @myclass.title %></h1>

  <p>
    <strong>時間:</strong>
    <%= @date + " " + @myclass.time_string %>
  </p>

  <p>
    <strong>名額:</strong>
    <%= @myclass.limit %>
  </p>

  <p>
    <strong>地點:</strong>
    <%= @myclass.classroom.title %>
  </p>

  <p>
    <strong>地址:</strong>
    <%= @myclass.classroom.address %>
  </p>
</div>


<% if @myclass.is_opened_for_signup %>
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h2>已報名</h2>
        <% if @safe.count == 0 %>
          <p>尚未有人報名</p>
        <% else %>
          <ol>
            <% @safe.each do |student|%>
              <li><%= student.name %></li>
            <% end %>
          </ol>
        <% end %>

      </div>
      <div class="col-md-6">
        <h2>候補</h2>
        <% if @back.count == 0 %>
          <p>沒有候補</p>
        <% else %>
          <ol>
            <% @back.each do |student|%>
              <li><%= student.name %></li>
            <% end %>
          </ol>
        <% end %>
     </div>
   </div>
   <div class="row">
      <div class="col-md-6">
        <h2>登記</h2>
        <div class="panel panel-default">
          <div class="panel-body">
            <%= render 'attendances/signup' %>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <h2>取消</h2>
        <div class="panel panel-default">
          <div class="panel-body">
            <%= render 'attendances/delete' %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2>這堂課還沒開放報名</h2>
      </div>
  </div>
<% end %>