config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'myclasses#index'
  resources :myclasses, only: [:index]
  get "/myclasses/:id/signup", to: 'myclasses#signup', as: 'signup_myclass'
  get '/myclasses/multi_signup', to: 'myclasses#multi_signup', as: 'multi_signup_myclass'
  get '/myclasses/show/:id', to: 'myclasses#show', as: 'myclass'
  get '/myclasses/showbetween', to: 'myclasses#showbetween', as: 'showbetween_myclass'

  get '/myclasses/:id/score', to: 'myclasses#score', as: 'score_myclass'

  resources :attendances, only: [:create, :show]
  delete "/attendances", to: 'attendances#destroy', as: 'delete_attendance'
  post "/attendances/multi_signup", to: 'attendances#multi_signup', as: 'multi_signup_attendances'
  post '/attendances/score', to: 'attendances#score', as: 'score_attendance'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>喬巴的教室</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "喬巴的教室", root_path, class: "navbar-brand" %>
          <!-- <a class="navbar-brand" href="#">喬巴的教室</a> -->
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <% home = params[:controller] == 'myclasses' && params[:action] == 'index' %>
            <% classes = params[:controller] == 'myclasses' && params[:action] == 'showbetween' %>
            <li class="<%= 'active' if home %>"><%= link_to "Home", root_path %></li>
            <li class="<%= 'active' if classes %>"><%= link_to '所有課程', showbetween_myclass_path %></li>
            <li ><%= link_to "Admin", admin_root_path %></li>

            <!-- <li><a href="#contact">Contact</a></li> -->
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


    <div class="container" id="my">

      <div class="starter-template">
        <%= yield %>
      </div>

    </div>

    <footer class="footer">
      <div class="container">
      	<div class="row">
      		<!-- <div class="col-md-12">
        		<%= link_to "administration", admin_root_path, :class => "btn btn-default"%>
        	</div> -->
        </div>
      </div>
    </footer>

</body>
</html>